apiVersion: apps/v1
kind: Deployment
metadata:
  name: hebi-{{ fedid }}
  namespace: hebi
spec:
  selector:
    matchLabels:
      app: hebi-{{ fedid }}
  replicas: 1
  template:
    metadata:
      labels:
        app: hebi-{{ fedid }}
    spec:
      serviceAccountName: hebi
      securityContext:
        runAsUser: {{ uid }}
        runAsGroup: {{ gid }}
      volumes:
        - name: dls
          hostPath:
            path: /dls
            type: Directory
        - name: home
          hostPath:
            path: /home
            type: Directory
      containers:
        - name: api
          image: gcr.io/diamond-pubreg/hebi/api:prod-savu-lite-4.0_2021.09-py37_0
          command: ["/bin/bash"]
          args: ["/webservice/run.sh"]
          securityContext:
            privileged: false
          ports:
            - containerPort: 5000
          env:
            - name: FEDID
              value: {{ fedid }}
          volumeMounts:
            - mountPath: /files/dls
              name: dls
              mountPropagation: HostToContainer
            - mountPath: /files/home
              name: home
              mountPropagation: HostToContainer
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 700m
              memory: 200Mi
        - name: web
          image: gcr.io/diamond-pubreg/hebi/web:prod-nginx-gzip
          command: ["/bin/sh"]
          args: ["/entrypoint.sh"]
          ports:
            - containerPort: 8080
          env:
            - name: FEDID
              value: {{ fedid }}
            - name: ACTIVATE_CAS_AUTH
              value: 'True'
            - name: SERVICE
              value: {{ service }}
            - name: CAS_SERVER
              value: {{ cas_server }}
            - name: ACTIVATE_WEBSOCKET
              value: 'True'
            - name: WEBSOCKET_SERVER
              value: {{ websocket_server }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
        - name: file-browser-server
          image: gcr.io/diamond-pubreg/hebi/file-browser-server:format-flag
          command: ["npm"]
          args: ["start"]
          ports:
            - containerPort: 8081
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /files/dls
              name: dls
              mountPropagation: HostToContainer
            - mountPath: /files/home
              name: home
              mountPropagation: HostToContainer
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              cpu: 150m
              memory: 50Mi
        - name: cas-authenticator
          image: gcr.io/diamond-pubreg/hebi/cas-authenticator:prod-bjoern
          command: ["python3.7"]
          args: ["cas-auth.py"]
          ports:
            - containerPort: 8090
          securityContext:
            privileged: false
          env:
            - name: FEDID
              value: {{ fedid }}
            - name: SERVICE
              value: {{ service }}
            - name: CAS_SERVER
              value: {{ cas_server }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cas-secret
                  key: jwt-key
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 115m
              memory: 50Mi
