apiVersion: apps/v1
kind: Deployment
metadata:
  name: hebi-launcher
  namespace: hebi
spec:
  selector:
    matchLabels:
      app: hebi-launcher
  replicas: 1
  template:
    metadata:
      labels:
        app: hebi-launcher
    spec:
      serviceAccountName: default
      securityContext:
        # k8s-hebi user
        runAsUser: 37676
        runAsGroup: 37820
      containers:
        - name: launcher
          image: gcr.io/diamond-pubreg/hebi/flask-launcher/launcher:prod
          command: ["python3.7"]
          args: ["launcher.py"]
          ports:
            - containerPort: 8085
          env:
            - name: FLASK_MODE
              value: 'production'
            - name: IN_CLUSTER
              value: 'True'
            - name: ALL_SESSIONS_CHECK_INTERVAL
              value: '20'
            - name: INACTIVE_SESSION_CHECK_INTERVAL
              value: '120'
            - name: SESSION_INACTIVITY_PERIOD
              value: '86400' # 24 hours
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cas-secret
                  key: jwt-key
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 700m
              memory: 200Mi
        - name: cas-auth
          image: gcr.io/diamond-pubreg/hebi/flask-launcher/cas-auth:prod
          command: ["python3.7"]
          args: ["cas-auth.py"]
          ports:
            - containerPort: 8086
          imagePullPolicy: Always
          env:
            - name: FLASK_MODE
              value: 'production'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cas-secret
                  key: jwt-key
          resources:
            limits:
              cpu: 115m
              memory: 50Mi
        - name: nginx
          image: gcr.io/diamond-pubreg/hebi/flask-launcher/nginx:prod
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 115m
              memory: 50Mi
